<?php

namespace CommitStripBundle\Repository;

//use Doctrine\ORM\Tools\Pagination\Paginator;
use CommitStripBundle\Entity\Card;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPrev(Card $card){

		$qb = $this->createQueryBuilder('c');

		$qb->where('c.nbcard < :nbcard')
		->andWhere('c.story = :story')
		->orderBy('c.nbcard', 'DESC')
		->setParameter('nbcard', $card->getNbcard())
		->setParameter('story', $card->getStory())
		->setMaxResults(1);

		return $qb
		->getQuery()
		->getOneOrNullResult();
	}

	public function getNext(Card $card){

		$qb = $this->createQueryBuilder('c');

		$qb->where('c.nbcard > :nbcard')
		->andWhere('c.story = :story')
		->orderBy('c.nbcard', 'ASC')
		->setParameter('nbcard', $card->getNbcard())
		->setParameter('story', $card->getStory())
		->setMaxResults(1);

		return $qb
		->getQuery()
		->getOneOrNullResult();
	}
}
