<?php

namespace CommitStripBundle\Repository;

//use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPrev($id){

		$qb = $this->createQueryBuilder('c');

		$qb->where('c.id < :patate')
		->orderBy('c.id', 'DESC')
		->setParameter('patate', $id)
		->setMaxResults( 1);

		return $qb
		->getQuery()
		->getOneOrNullResult();
	}
	public function getNext($id){

		$qb = $this->createQueryBuilder('c');

		$qb->where('c.id > :id')
		->orderBy('c.id', 'ASC')
		->setParameter('id', $id)
		->setMaxResults( 1);

		return $qb
		->getQuery()
		->getOneOrNullResult();
	}
}
