wcs_commit_strip_homepage:
    path:     /
    defaults: { _controller: WCSCommitStripBundle:Default:index }

wcs_commit_strip_card:
    path:     /card/{nbcard}
    defaults: { _controller: WCSCommitStripBundle:Card:showCard }