wcs_commit_strip_homepage:
    path:     /
    defaults: { _controller: WCSCommitStripBundle:Default:index }

wcs_commit_strip_book:
    path:    /{id}
    defaults: { _controller: WCSCommitStripBundle:Default:index }
