commit_strip_homepage:
    path:     /
    defaults: { _controller: CommitStripBundle:Default:index }

card_homepage:
    path:     /card
    defaults: { _controller: CommitStripBundle:Default:card }
