commit_strip_homepage:
    path:     /
    defaults: { _controller: CommitStripBundle:Default:index }
commit_strip_show:
    path:     /{id}
    defaults:
        _controller: CommitStripBundle:Default:show
        id: 1
    requirements:
        id: \d+